### PR TITLE
Add support for Atlas being an Opencensus target

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by brharrington** [comment]
It'll take some time to review this. At first glance it adds a lot of dependencies which is generally something we want to avoid for the thin clients. Ideally we have no dependencies out side of the standard library for a language. It might be better as a separate extension library.

**Comment by sargun** [comment]
@brharrington It requires access to some private methods, namely `newId` and `registry.newMeter`.

**Comment by sargun** [comment]
See: https://github.com/Netflix/spectator-go/pull/36

**Comment by brharrington** [comment]
Probably won't have time today, but will try to take a look in detail this weekend.

**Pull request closed without merging**
